versions:
  "1.0.0":
    folder: all
  "1.0.1":
    folder: all
  "1.0.2":
    folder: all
  "1.0.3":
    folder: all
  "1.0.4":
    folder: all
  "1.0.5":
    folder: all
  "1.0.6":
    folder: all
  "1.1.0":
    folder: all
  "1.1.1":
    folder: all
  "1.1.2":
    folder: all
  "1.2.0":
    folder: all
  "1.2.1":
    folder: all
  "1.2.2":
    folder: all
  "1.3.0":
    folder: all
  "2.0.0":
    folder: all
  "2.0.1":
    folder: all
  "2.1.0":
    folder: all
  "2.1.1":
    folder: all
  "2.1.2":
    folder: all
  "2.1.3":
    folder: all
  "2.1.4":
    folder: all
  "2.2.4":
    folder: all
